export const TEXT = {
  SOPHIA: "Sophia",
  HEADER: "Header",
  FOOTER: "Footer",
  NOT_FOUND: "404 Page Not Found",
  FOOTER_TEXT: "SHOPHIA. All Rights Reserved.",
  HOME: "HOME",
  ABOUT: "ABOUT US",
  PRIVACY: "Privacy Policy",
  TERMS: "Terms & Conditions",
  WELCOME: "Welcome to ",
  AI_PLATFORM: "The AI platform redefining connected care.",
  READ_MORE: "Read More",
  PATIENT: "Patient",
  FAMILY: "Family",
  DOCTOR: "Doctor",
  CAREGIVER: "Caregiver",
  SIGN_IN: "Sign In",
  FORGOT_PASSWORD: "Forgot your Password?",
  CREATE_ACCOUNT: "Create Account",
  DONT_ACCOUNT: "Don’t have an account?",
  SIGN_ACCOUNT: "Sign in to your healthcare account",
  USERNAME: "Username",
  ENTER_USERNAME: "Enter your username",
  USER_REQUIRED: "Username is required.",
  USER_MIN: "Username must be at least 3 characters long.",
  USER_MAX: "Username cannot exceed 30 characters.",
  PASSWORD: "Password",
  ENTER_PASSWORD: "Enter your password",
  PASSWORD_REQUIRED: "Password is required.",
  PASSWORD_MIN: "Password must be at least 3 characters long.",
  PASSWORD_MAX: "Password cannot exceed 10 characters.",
};
