export const TEXT = {
  SOPHIA: "Sophia",
  WELCOME_BACK: "Welcome back",
  LOGIN_ACC: "Login to your account",
  HEADER: "Header",
  FOOTER: "Footer",
  NOT_FOUND: "404 Page Not Found",
  FOOTER_TEXT: "SHOPHIA. All Rights Reserved.",
  HOME: "HOME",
  ABOUT: "ABOUT US",
  PRIVACY: "Privacy Policy",
  TERMS: "Terms & Conditions",
  PATIENT: "Patient",
  FAMILY: "Family",
  DOCTOR: "Doctor",
  CAREGIVER: "Caregiver",
  SIGN_IN: "Sign In",
  SUBMIT: "Submit",
  PASSWORD: "Password",
  ENTER_PASSWORD: "Enter your password",
  ENTER_PASSWORD_TEXT: "Enter password",
  PASSWORD_REQUIRED: "Password is required.",
  PASSWORD_MIN: "Password must be at least 6 characters long.",
  PASSWORD_MAX: "Password cannot exceed 15 characters.",
  PASSWORD_INCLUDE:
    "Password must include uppercase, lowercase, number & special character.",
  EMAIL_ID: "Email id",
  ENTER_EMAIL: "Enter your email id",
  PLEASE_ENTER_EMAIL: "Email is required.",
  ENTER_VALID_EMAIL: "Enter valid email address.",
  EMAIL: "Email",
  ENTER_YOU_EMAIL: "Enter your email",
  ENTER_EMAIL: "Enter email",
  PHONE_NUMBER: "Phone Number",
  ENTER_PHONE_NUMBER: "Enter phone number",
  USERS: "Users",
  PATIENTS: "Patients",
  FAMILY_MEMBER: "Family Member",
  DOCTORS: "Doctors",
  CAREGIVERS: "Cargivers",
  DETAIL: "Details",
  ACTION: "Action",
  AGE: "Age",
  YEARS: "years",
  BASIC_INFO: "Basic Info",
  OTHER_INFO: "Other Info",
  MRN_NO: "MRN Number",
  ENTER_MRN_NO: "Enter your MRN Number",
  EMERGENCY_TITLE: "Emergency Contact Info",
  OPTIONAL: "(Optional)",
  EMERGENCY_NAME: "Name",
  EMERGENCY_NAME_PLACEHOLDER: "Enter name",
  EMERGENCY_RELATION: "Relationship",
  EMERGENCY_RELATION_PLACEHOLDER: "Enter relationship",
  BIRTH_DATE: "Birth Date",
  BIRTH_DATE_PLACEHOLDER: "Enter Birth date",
  PHONE_NUMBER: "Phone Number",
  PHONE_PLACEHOLDER: "Enter phone number",
  ID_PHOTO: "ID Photo",
  CONSULTING: "Consulting",
  SCHEDULE: "Schedule",
  FAMILY_FRNDS: "Family and Friends",
  QUE_CARE_TEAM: "Question for Care Team",
  PATIENT_HOSTORY: "Patient History",
  EXIST_QUE: "Existing Questions",
  VIEW_ALL: "VIEW ALL",
  VALIDATE: "Validate",
  DOCTOR_LIST: "Doctors List",
  CAREGIVER_LIST: "Caregivers List",
  NPI_NO: "NPI Number",
  NPI_NO_PLACEHOLDER: "Enter NPI Number",
  CAREGIVER_ROTARY: "Caregiver Rotary Role",
  CAREGIVER_ROTARY_PLACEHOLDER: "Enter Caregiver Rotary Role",
  GENRIC_ROLE:
    "IF THE Caregiver have a generic role.(such as nurse, PT, CM/Sw)",
  GENRIC_ROLE_PLACEHOLDER: "Enter generic role",
  SPECIALIZATION: "Specialization",
  SPECIALIZATION_PLACEHOLDER: "Enter Specialization",
};
