export const TEXT = {
  SOPHIA: "Sophia",
  HEADER: "Header",
  FOOTER: "Footer",
  NOT_FOUND: "404 Page Not Found",
  FOOTER_TEXT: "SHOPHIA. All Rights Reserved.",
  HOME: "HOME",
  ABOUT: "ABOUT US",
  PRIVACY: "Privacy Policy",
  TERMS: "Terms & Conditions",
  WELCOME: "Welcome to ",
  AI_PLATFORM: "The AI platform redefining connected care.",
  READ_MORE: "Read More",
  PATIENT: "Patient",
  FAMILY: "Family",
  DOCTOR: "Doctor",
  CAREGIVER: "Caregiver",
  SIGN_IN: "Sign In",
  SEND_LINK: "Send Link",
  FORGOT_PASSWORD: "Forgot your Password?",
  CREATE_ACCOUNT: "Create Account",
  DONT_ACCOUNT: "Don’t have an account?",
  SIGN_ACCOUNT: "Sign in to your healthcare account",
  FORGOT_TEXT:
    "Enter your email address below, and we’ll send you a link to reset it.",
  BACK_SIGNIN: "Back to Sign In",
  RESET_PASSWORD: "Reset your password?",
  RESET_TEXT: "Please fill out this form to reset your password.",
  PASSWORD_NOT_MATCH: "Passwords do not match",
  ENTER_OTP: "Please enter the complete OTP",
  SUBMIT: "Submit",
  USERNAME: "Username",
  ENTER_USERNAME: "Enter your username",
  USER_REQUIRED: "Username is required.",
  USER_MIN: "Username must be at least 3 characters long.",
  USER_MAX: "Username cannot exceed 30 characters.",
  PASSWORD: "Password",
  ENTER_PASSWORD: "Enter your password",
  PASSWORD_REQUIRED: "Password is required.",
  PASSWORD_MIN: "Password must be at least 3 characters long.",
  PASSWORD_MAX: "Password cannot exceed 10 characters.",
  CONFIRM_PASSWORD: "Confirm Password",
  ENTER_CONFIRM_PASSWORD: "Enter your confirm password",
  CONFIRM_PASSWORD_REQUIRED: "Confirm password is required.",
  CONFIRM_PASSWORD_MIN: "Confirm password must be at least 3 characters long.",
  CONFIRM_PASSWORD_MAX: "Confirm password cannot exceed 10 characters.",
  EMAIL_ID: "Email id",
  ENTER_EMAIL: "Enter your email id",
  PLEASE_ENTER_EMAIL: "Please enter email",
  ENTER_VALID_EMAIL: "Please enter valid email",
};
